repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-json
      - id: pretty-format-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: run isort .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: black
        name: black
        entry: run black .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: flake8
        name: flake8
        entry: run flake8 .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: mypy
        name: mypy
        entry: run mypy .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      # - id: pytest
      #   name: pytest
      #   entry: run pytest
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true
      #   stages: [push]